// src/lib/photoStore.ts
//
// OPFS-backed photo store for food library entries.
// Invariants (see CLAUDE.md rules #5 and #6 + .planning/research/PITFALLS.md §Pitfall 8):
//   1. Photos live in OPFS — NEVER as Dexie blobs. Dexie records store only the filename (photoKey).
//   2. Photos MUST be resized (≤800×800 at WebP quality 0.8) BEFORE savePhoto() is called.
//      Raw iPhone photos (~4-5MB) will fill quota and crash the tab.
//   3. Filenames are generated by savePhoto() as `food-<uuid>.webp`. Callers never construct them.
//
// Locked by CONTEXT.md D-07: WebP @ 0.8 (NOT JPEG @ 0.7 — CLAUDE.md rule #5 must be updated
// by Plan 03 to match this decision).

const PHOTO_DIR = 'food-photos';

async function getDir(): Promise<FileSystemDirectoryHandle> {
  const root = await navigator.storage.getDirectory();
  return root.getDirectoryHandle(PHOTO_DIR, { create: true });
}

/** Save a resized blob to OPFS and return the generated filename (photoKey). */
export async function savePhoto(blob: Blob): Promise<string> {
  const key = `food-${crypto.randomUUID()}.webp`;
  const dir = await getDir();
  const fh = await dir.getFileHandle(key, { create: true });
  const writable = await fh.createWritable();
  await writable.write(blob);
  await writable.close();
  return key;
}

/** Read a photo back as a Blob. Caller is responsible for object-URL lifecycle. */
export async function loadPhoto(filename: string): Promise<Blob> {
  const dir = await getDir();
  const fh = await dir.getFileHandle(filename);
  return await fh.getFile();
}

export async function deletePhoto(filename: string): Promise<void> {
  const dir = await getDir();
  await dir.removeEntry(filename);
}

/**
 * Resize a user-picked File to ≤ maxDim (default 800px) on its longest edge,
 * encoded as WebP at quality 0.8 (per CONTEXT.md D-07).
 *
 * EXIF orientation is handled by createImageBitmap's imageOrientation option —
 * supported on Chrome 90+, Safari 15+, Firefox 103+ (all target browsers for
 * iOS/Android home-screen PWAs in 2026).
 */
export async function resizePhoto(
  file: File,
  maxDim = 800,
  quality = 0.8,
): Promise<Blob> {
  const bitmap = await createImageBitmap(file, { imageOrientation: 'from-image' });
  const scale = Math.min(1, maxDim / Math.max(bitmap.width, bitmap.height));
  const w = Math.round(bitmap.width * scale);
  const h = Math.round(bitmap.height * scale);

  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('2D canvas context unavailable');
  ctx.drawImage(bitmap, 0, 0, w, h);

  return await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error('canvas.toBlob returned null'))),
      'image/webp',
      quality,
    );
  });
}
